dataset: !!str icbhi_t11

wavs_dir: !!str /home/ncl/yh/odio/datasets/lung/icbhi_chunks_16k/
label_file: !!str /home/ncl/yh/odio/datasets/lung/icbhi_t11.txt

official_split: !!str /home/ncl/yh/UNOprocess/icbhi_data/icbhi_train_test_split.csv

batch_size: 64
val_batch_size: 256
num_workers: 8
num_classes: 4  # RSC-1: 4, RSC-2: 2, RDC-1: 3, RDC-2: 2
kwargs_:
    labels_sep: !!str "\t"
    normal_class_label: 0